import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const jakartaSans = localFont({
  src: "./fonts/PlusJakartaSans-VariableFont_wght.ttf",
  variable: "--font-jakarta-sans",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Hackthon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jakartaSans.variable} antialiased font-jakarta`}
      >
         <header className="w-full flex items-center justify-between p-5 bg-slate-50 border-b">
    <Link href="/" className="instagrad text-4xl font-extrabold text-transparent bg-clip-text">
            FLUENT Match
          </Link>

          <div className="space-x-4">
            <Link className="p-3 px-8 rounded-full font-semibold border-2 text-[#FC4B29] border-[#FC4B29]" href={"/"}>Brand</Link>
            <Link className="p-3 px-8 rounded-full font-semibold border-2 bg-[#FC4B29] border-[#FC4B29] text-white" href={"/influencer/account"}>Creator</Link>
          </div>
    </header>
        {children}
      </body>
    </html>
  );
}
